set(_CATKIN_CURRENT_PACKAGE "local_planner")
set(local_planner_VERSION "0.0.0")
set(local_planner_MAINTAINER "matt <matt@todo.todo>")
set(local_planner_PACKAGE_FORMAT "2")
set(local_planner_BUILD_DEPENDS "rospy" "std_msgs" "nav_msgs" "convex_decomposer" "snapstack_msgs" "geometry_msgs" "shape_msgs")
set(local_planner_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(local_planner_BUILDTOOL_DEPENDS "catkin")
set(local_planner_BUILDTOOL_EXPORT_DEPENDS )
set(local_planner_EXEC_DEPENDS "rospy" "std_msgs" "nav_msgs" "convex_decomposer" "snapstack_msgs" "geometry_msgs" "shape_msgs")
set(local_planner_RUN_DEPENDS "rospy" "std_msgs" "nav_msgs" "convex_decomposer" "snapstack_msgs" "geometry_msgs" "shape_msgs")
set(local_planner_TEST_DEPENDS )
set(local_planner_DOC_DEPENDS )
set(local_planner_URL_WEBSITE "")
set(local_planner_URL_BUGTRACKER "")
set(local_planner_URL_REPOSITORY "")
set(local_planner_DEPRECATED "")