// Generated by gencpp from file convex_decomposer/CvxDecomp.msg
// DO NOT EDIT!


#ifndef CONVEX_DECOMPOSER_MESSAGE_CVXDECOMP_H
#define CONVEX_DECOMPOSER_MESSAGE_CVXDECOMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <convex_decomposer/Polyhedron.h>

namespace convex_decomposer
{
template <class ContainerAllocator>
struct CvxDecomp_
{
  typedef CvxDecomp_<ContainerAllocator> Type;

  CvxDecomp_()
    : header()
    , polyhedra()  {
    }
  CvxDecomp_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , polyhedra(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::convex_decomposer::Polyhedron_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::convex_decomposer::Polyhedron_<ContainerAllocator> >::other >  _polyhedra_type;
  _polyhedra_type polyhedra;





  typedef boost::shared_ptr< ::convex_decomposer::CvxDecomp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::convex_decomposer::CvxDecomp_<ContainerAllocator> const> ConstPtr;

}; // struct CvxDecomp_

typedef ::convex_decomposer::CvxDecomp_<std::allocator<void> > CvxDecomp;

typedef boost::shared_ptr< ::convex_decomposer::CvxDecomp > CvxDecompPtr;
typedef boost::shared_ptr< ::convex_decomposer::CvxDecomp const> CvxDecompConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::convex_decomposer::CvxDecomp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::convex_decomposer::CvxDecomp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::convex_decomposer::CvxDecomp_<ContainerAllocator1> & lhs, const ::convex_decomposer::CvxDecomp_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.polyhedra == rhs.polyhedra;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::convex_decomposer::CvxDecomp_<ContainerAllocator1> & lhs, const ::convex_decomposer::CvxDecomp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace convex_decomposer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::convex_decomposer::CvxDecomp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::convex_decomposer::CvxDecomp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::convex_decomposer::CvxDecomp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::convex_decomposer::CvxDecomp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_decomposer::CvxDecomp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::convex_decomposer::CvxDecomp_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::convex_decomposer::CvxDecomp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa0b44be5161dc2f552ca9c3ef45157c";
  }

  static const char* value(const ::convex_decomposer::CvxDecomp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa0b44be5161dc2fULL;
  static const uint64_t static_value2 = 0x552ca9c3ef45157cULL;
};

template<class ContainerAllocator>
struct DataType< ::convex_decomposer::CvxDecomp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "convex_decomposer/CvxDecomp";
  }

  static const char* value(const ::convex_decomposer::CvxDecomp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::convex_decomposer::CvxDecomp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"convex_decomposer/Polyhedron[] polyhedra\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: convex_decomposer/Polyhedron\n"
"shape_msgs/Plane[] planes\n"
"\n"
"================================================================================\n"
"MSG: shape_msgs/Plane\n"
"# Representation of a plane, using the plane equation ax + by + cz + d = 0\n"
"\n"
"# a := coef[0]\n"
"# b := coef[1]\n"
"# c := coef[2]\n"
"# d := coef[3]\n"
"\n"
"float64[4] coef\n"
;
  }

  static const char* value(const ::convex_decomposer::CvxDecomp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::convex_decomposer::CvxDecomp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.polyhedra);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CvxDecomp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::convex_decomposer::CvxDecomp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::convex_decomposer::CvxDecomp_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "polyhedra[]" << std::endl;
    for (size_t i = 0; i < v.polyhedra.size(); ++i)
    {
      s << indent << "  polyhedra[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::convex_decomposer::Polyhedron_<ContainerAllocator> >::stream(s, indent + "    ", v.polyhedra[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEX_DECOMPOSER_MESSAGE_CVXDECOMP_H
