set(_CATKIN_CURRENT_PACKAGE "master_node")
set(master_node_VERSION "0.0.0")
set(master_node_MAINTAINER "matt <matt@todo.todo>")
set(master_node_PACKAGE_FORMAT "2")
set(master_node_BUILD_DEPENDS "local_planner" "rospy" "snapstack_msgs" "nav_msgs" "geom_msgs" "std_msgs" "message_generation" "tf")
set(master_node_BUILD_EXPORT_DEPENDS "local_planner" "rospy" "snapstack_msgs" "std_msgs")
set(master_node_BUILDTOOL_DEPENDS "catkin")
set(master_node_BUILDTOOL_EXPORT_DEPENDS )
set(master_node_EXEC_DEPENDS "local_planner" "rospy" "snapstack_msgs" "std_msgs" "nav_msgs" "geometry_msgs" "message_runtime" "tf")
set(master_node_RUN_DEPENDS "local_planner" "rospy" "snapstack_msgs" "std_msgs" "nav_msgs" "geometry_msgs" "message_runtime" "tf")
set(master_node_TEST_DEPENDS )
set(master_node_DOC_DEPENDS )
set(master_node_URL_WEBSITE "")
set(master_node_URL_BUGTRACKER "")
set(master_node_URL_REPOSITORY "")
set(master_node_DEPRECATED "")