#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/sangita/project_ws/AER1516/devel_isolated/master_node:/home/sangita/project_ws/AER1516/devel_isolated/local_planner:/home/sangita/project_ws/AER1516/devel_isolated/global_planner:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper_ros:/home/sangita/project_ws/AER1516/devel_isolated/faster:/home/sangita/project_ws/AER1516/devel_isolated/snapstack_msgs:/home/sangita/project_ws/AER1516/devel_isolated/map_simulator:/home/sangita/project_ws/AER1516/devel_isolated/jps3d:/home/sangita/project_ws/AER1516/devel_isolated/depthmap_filter:/home/sangita/project_ws/AER1516/devel_isolated/fla_utils:/home/sangita/project_ws/AER1516/devel_isolated/fla_msgs:/home/sangita/project_ws/AER1516/devel_isolated/faster_msgs:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_utils:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_msgs:/home/sangita/project_ws/AER1516/devel_isolated/convex_decomposer:/home/sangita/project_ws/AER1516/devel_isolated/catkin_simple:/home/sangita/project_ws/AER1516/devel_isolated/acl_sim:/home/sangita/project_ws/AER1516/devel:/opt/ros/melodic:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper:/home/sangita/project_ws/AER1516/devel_isolated/decomp_util'
export LD_LIBRARY_PATH='/home/sangita/project_ws/AER1516/devel_isolated/local_planner/lib:/home/sangita/project_ws/AER1516/devel_isolated/global_planner/lib:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper_ros/lib:/home/sangita/project_ws/AER1516/devel_isolated/faster/lib:/home/sangita/project_ws/AER1516/devel_isolated/snapstack_msgs/lib:/home/sangita/project_ws/AER1516/devel_isolated/map_simulator/lib:/home/sangita/project_ws/AER1516/devel_isolated/jps3d/lib:/home/sangita/project_ws/AER1516/devel_isolated/depthmap_filter/lib:/home/sangita/project_ws/AER1516/devel_isolated/fla_utils/lib:/home/sangita/project_ws/AER1516/devel_isolated/fla_msgs/lib:/home/sangita/project_ws/AER1516/devel_isolated/faster_msgs/lib:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_utils/lib:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_msgs/lib:/home/sangita/project_ws/AER1516/devel_isolated/convex_decomposer/lib:/home/sangita/project_ws/AER1516/devel_isolated/catkin_simple/lib:/home/sangita/project_ws/AER1516/devel_isolated/acl_sim/lib:/home/sangita/project_ws/AER1516/devel/lib:/opt/ros/melodic/lib:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper/lib'
export PATH='/opt/ros/melodic/bin:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper/bin:/home/sangita/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export ROSLISP_PACKAGE_DIRECTORIES="/home/sangita/project_ws/AER1516/devel_isolated/master_node/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/sangita/project_ws/AER1516/src/master_node:$ROS_PACKAGE_PATH"