set(_CATKIN_CURRENT_PACKAGE "octomap_listener")
set(octomap_listener_VERSION "0.0.0")
set(octomap_listener_MAINTAINER "furqan <furqan@todo.todo>")
set(octomap_listener_PACKAGE_FORMAT "2")
set(octomap_listener_BUILD_DEPENDS "roscpp" "octomap" "snapstack_msgs")
set(octomap_listener_BUILD_EXPORT_DEPENDS )
set(octomap_listener_BUILDTOOL_DEPENDS "catkin")
set(octomap_listener_BUILDTOOL_EXPORT_DEPENDS )
set(octomap_listener_EXEC_DEPENDS "octomap" "snapstack_msgs")
set(octomap_listener_RUN_DEPENDS "octomap" "snapstack_msgs")
set(octomap_listener_TEST_DEPENDS )
set(octomap_listener_DOC_DEPENDS )
set(octomap_listener_URL_WEBSITE "")
set(octomap_listener_URL_BUGTRACKER "")
set(octomap_listener_URL_REPOSITORY "")
set(octomap_listener_DEPRECATED "")