set(_CATKIN_CURRENT_PACKAGE "snapstack_msgs")
set(snapstack_msgs_VERSION "0.0.0")
set(snapstack_msgs_MAINTAINER "Brett Lopez <btlopez@mit.edu>, Parker Lusk <plusk@mit.edu>")
set(snapstack_msgs_PACKAGE_FORMAT "2")
set(snapstack_msgs_BUILD_DEPENDS "message_runtime" "std_msgs" "std_srvs" "geometry_msgs" "nav_msgs" "actionlib_msgs")
set(snapstack_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs" "std_srvs" "geometry_msgs" "nav_msgs" "actionlib_msgs")
set(snapstack_msgs_BUILDTOOL_DEPENDS "catkin")
set(snapstack_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(snapstack_msgs_EXEC_DEPENDS "message_runtime" "std_msgs" "std_srvs" "geometry_msgs" "nav_msgs" "actionlib_msgs")
set(snapstack_msgs_RUN_DEPENDS "message_runtime" "std_msgs" "std_srvs" "geometry_msgs" "nav_msgs" "actionlib_msgs")
set(snapstack_msgs_TEST_DEPENDS )
set(snapstack_msgs_DOC_DEPENDS )
set(snapstack_msgs_URL_WEBSITE "")
set(snapstack_msgs_URL_BUGTRACKER "")
set(snapstack_msgs_URL_REPOSITORY "")
set(snapstack_msgs_DEPRECATED "")