set(_CATKIN_CURRENT_PACKAGE "depthmap_filter")
set(depthmap_filter_VERSION "0.0.0")
set(depthmap_filter_MAINTAINER "W. Nicholas Greene <wng@csail.mit.edu>")
set(depthmap_filter_PACKAGE_FORMAT "2")
set(depthmap_filter_BUILD_DEPENDS "roscpp" "nodelet" "sensor_msgs" "fla_msgs" "image_transport" "message_filters" "cv_bridge" "fla_utils")
set(depthmap_filter_BUILD_EXPORT_DEPENDS "roscpp" "nodelet" "sensor_msgs" "fla_msgs" "image_transport" "message_filters" "cv_bridge" "fla_utils")
set(depthmap_filter_BUILDTOOL_DEPENDS "catkin")
set(depthmap_filter_BUILDTOOL_EXPORT_DEPENDS )
set(depthmap_filter_EXEC_DEPENDS "roscpp" "nodelet" "sensor_msgs" "fla_msgs" "image_transport" "message_filters" "cv_bridge" "fla_utils")
set(depthmap_filter_RUN_DEPENDS "roscpp" "nodelet" "sensor_msgs" "fla_msgs" "image_transport" "message_filters" "cv_bridge" "fla_utils")
set(depthmap_filter_TEST_DEPENDS )
set(depthmap_filter_DOC_DEPENDS )
set(depthmap_filter_URL_WEBSITE "")
set(depthmap_filter_URL_BUGTRACKER "")
set(depthmap_filter_URL_REPOSITORY "")
set(depthmap_filter_DEPRECATED "")