(cl:in-package snapstack_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          P-VAL
          P
          P_REF-VAL
          P_REF
          P_ERR-VAL
          P_ERR
          P_ERR_INT-VAL
          P_ERR_INT
          V-VAL
          V
          V_REF-VAL
          V_REF
          V_ERR-VAL
          V_ERR
          A_FF-VAL
          A_FF
          A_FB-VAL
          A_FB
          J_FF-VAL
          J_FF
          J_FB-VAL
          J_FB
          Q-VAL
          Q
          Q_REF-VAL
          Q_REF
          RPY-VAL
          RPY
          RPY_REF-VAL
          RPY_REF
          W-VAL
          W
          W_REF-VAL
          W_REF
          F_W-VAL
          F_W
          THRUST-VAL
          THRUST
          THROTTLE-VAL
          THROTTLE
          POWER-VAL
          POWER
))