set(_CATKIN_CURRENT_PACKAGE "convex_decomposer")
set(convex_decomposer_VERSION "0.0.0")
set(convex_decomposer_MAINTAINER "evr <evr@todo.todo>")
set(convex_decomposer_PACKAGE_FORMAT "2")
set(convex_decomposer_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(convex_decomposer_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(convex_decomposer_BUILDTOOL_DEPENDS "catkin")
set(convex_decomposer_BUILDTOOL_EXPORT_DEPENDS )
set(convex_decomposer_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(convex_decomposer_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(convex_decomposer_TEST_DEPENDS )
set(convex_decomposer_DOC_DEPENDS )
set(convex_decomposer_URL_WEBSITE "")
set(convex_decomposer_URL_BUGTRACKER "")
set(convex_decomposer_URL_REPOSITORY "")
set(convex_decomposer_DEPRECATED "")