set(_CATKIN_CURRENT_PACKAGE "acl_sim")
set(acl_sim_VERSION "0.0.0")
set(acl_sim_MAINTAINER "brett <brett@todo.todo>")
set(acl_sim_PACKAGE_FORMAT "1")
set(acl_sim_BUILD_DEPENDS "gazebo_plugins" "roscpp" "gazebo_ros" "message_to_tf" "robot_state_publisher")
set(acl_sim_BUILD_EXPORT_DEPENDS "gazebo_plugins" "roscpp" "gazebo_ros" "message_to_tf" "robot_state_publisher")
set(acl_sim_BUILDTOOL_DEPENDS "catkin")
set(acl_sim_BUILDTOOL_EXPORT_DEPENDS )
set(acl_sim_EXEC_DEPENDS "gazebo_plugins" "roscpp" "gazebo_ros" "message_to_tf" "robot_state_publisher")
set(acl_sim_RUN_DEPENDS "gazebo_plugins" "roscpp" "gazebo_ros" "message_to_tf" "robot_state_publisher")
set(acl_sim_TEST_DEPENDS )
set(acl_sim_DOC_DEPENDS )
set(acl_sim_URL_WEBSITE "")
set(acl_sim_URL_BUGTRACKER "")
set(acl_sim_URL_REPOSITORY "")
set(acl_sim_DEPRECATED "")