set(_CATKIN_CURRENT_PACKAGE "decomp_ros_utils")
set(decomp_ros_utils_VERSION "0.0.0")
set(decomp_ros_utils_MAINTAINER "sikang <sikang@todo.todo>")
set(decomp_ros_utils_PACKAGE_FORMAT "2")
set(decomp_ros_utils_BUILD_DEPENDS "catkin_simple" "roscpp" "rviz" "decomp_ros_msgs")
set(decomp_ros_utils_BUILD_EXPORT_DEPENDS "roscpp" "rviz" "decomp_ros_msgs")
set(decomp_ros_utils_BUILDTOOL_DEPENDS "catkin")
set(decomp_ros_utils_BUILDTOOL_EXPORT_DEPENDS )
set(decomp_ros_utils_EXEC_DEPENDS "roscpp" "rviz" "decomp_ros_msgs")
set(decomp_ros_utils_RUN_DEPENDS "roscpp" "rviz" "decomp_ros_msgs")
set(decomp_ros_utils_TEST_DEPENDS )
set(decomp_ros_utils_DOC_DEPENDS )
set(decomp_ros_utils_URL_WEBSITE "")
set(decomp_ros_utils_URL_BUGTRACKER "")
set(decomp_ros_utils_URL_REPOSITORY "")
set(decomp_ros_utils_DEPRECATED "")