set(_CATKIN_CURRENT_PACKAGE "decomp_ros_msgs")
set(decomp_ros_msgs_VERSION "0.0.0")
set(decomp_ros_msgs_MAINTAINER "sikang <sikang@seas.upenn.edu>")
set(decomp_ros_msgs_PACKAGE_FORMAT "2")
set(decomp_ros_msgs_BUILD_DEPENDS "catkin_simple" "geometry_msgs" "message_generation" "message_runtime")
set(decomp_ros_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "message_generation" "message_runtime")
set(decomp_ros_msgs_BUILDTOOL_DEPENDS "catkin")
set(decomp_ros_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(decomp_ros_msgs_EXEC_DEPENDS "geometry_msgs" "message_generation" "message_runtime")
set(decomp_ros_msgs_RUN_DEPENDS "geometry_msgs" "message_generation" "message_runtime")
set(decomp_ros_msgs_TEST_DEPENDS )
set(decomp_ros_msgs_DOC_DEPENDS )
set(decomp_ros_msgs_URL_WEBSITE "")
set(decomp_ros_msgs_URL_BUGTRACKER "")
set(decomp_ros_msgs_URL_REPOSITORY "")
set(decomp_ros_msgs_DEPRECATED "")