set(_CATKIN_CURRENT_PACKAGE "faster_msgs")
set(faster_msgs_VERSION "0.0.0")
set(faster_msgs_MAINTAINER "Jesus Tordesillas Torres <jtorde@mit.edu>")
set(faster_msgs_PACKAGE_FORMAT "1")
set(faster_msgs_BUILD_DEPENDS "message_generation" "std_msgs" "std_srvs" "geometry_msgs" "nav_msgs" "actionlib_msgs")
set(faster_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs" "std_srvs" "geometry_msgs" "nav_msgs" "actionlib_msgs")
set(faster_msgs_BUILDTOOL_DEPENDS "catkin")
set(faster_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(faster_msgs_EXEC_DEPENDS "message_runtime" "std_msgs" "std_srvs" "geometry_msgs" "nav_msgs" "actionlib_msgs")
set(faster_msgs_RUN_DEPENDS "message_runtime" "std_msgs" "std_srvs" "geometry_msgs" "nav_msgs" "actionlib_msgs")
set(faster_msgs_TEST_DEPENDS )
set(faster_msgs_DOC_DEPENDS )
set(faster_msgs_URL_WEBSITE "")
set(faster_msgs_URL_BUGTRACKER "")
set(faster_msgs_URL_REPOSITORY "")
set(faster_msgs_DEPRECATED "")