set(_CATKIN_CURRENT_PACKAGE "faster")
set(faster_VERSION "0.0.0")
set(faster_MAINTAINER "Jesus Tordesillas Torres <jtorde@mit.edu>")
set(faster_PACKAGE_FORMAT "1")
set(faster_BUILD_DEPENDS "roscpp" "rospy" "jps3d" "jps3d" "snapstack_msgs" "snapstack_msgs" "decomp_util" "decomp_ros_utils" "tf2_sensor_msgs" "message_generation")
set(faster_BUILD_EXPORT_DEPENDS "message_runtime")
set(faster_BUILDTOOL_DEPENDS "catkin")
set(faster_BUILDTOOL_EXPORT_DEPENDS )
set(faster_EXEC_DEPENDS "message_runtime")
set(faster_RUN_DEPENDS "message_runtime")
set(faster_TEST_DEPENDS )
set(faster_DOC_DEPENDS )
set(faster_URL_WEBSITE "")
set(faster_URL_BUGTRACKER "")
set(faster_URL_REPOSITORY "")
set(faster_DEPRECATED "")