set(_CATKIN_CURRENT_PACKAGE "global_mapper_ros")
set(global_mapper_ros_VERSION "1.1.3")
set(global_mapper_ros_MAINTAINER "Jake Ware <jakeware@mit.edu>")
set(global_mapper_ros_PACKAGE_FORMAT "2")
set(global_mapper_ros_BUILD_DEPENDS "roscpp" "nodelet" "fla_utils" "pcl_ros" "pcl_msgs" "pcl_conversions" "tf2_ros" "nav_msgs" "visualization_msgs" "tf2_sensor_msgs" "message_generation" "image_transport" "cv_bridge" "global_mapper" "fla_msgs" "snapstack_msgs")
set(global_mapper_ros_BUILD_EXPORT_DEPENDS "roscpp" "nodelet" "fla_utils" "pcl_ros" "pcl_msgs" "pcl_conversions" "tf2_ros" "nav_msgs" "visualization_msgs" "tf2_sensor_msgs" "message_generation" "image_transport" "cv_bridge" "global_mapper" "fla_msgs" "snapstack_msgs")
set(global_mapper_ros_BUILDTOOL_DEPENDS "catkin")
set(global_mapper_ros_BUILDTOOL_EXPORT_DEPENDS )
set(global_mapper_ros_EXEC_DEPENDS "roscpp" "nodelet" "fla_utils" "pcl_ros" "pcl_msgs" "pcl_conversions" "tf2_ros" "nav_msgs" "visualization_msgs" "tf2_sensor_msgs" "message_generation" "image_transport" "cv_bridge" "global_mapper" "fla_msgs" "snapstack_msgs")
set(global_mapper_ros_RUN_DEPENDS "roscpp" "nodelet" "fla_utils" "pcl_ros" "pcl_msgs" "pcl_conversions" "tf2_ros" "nav_msgs" "visualization_msgs" "tf2_sensor_msgs" "message_generation" "image_transport" "cv_bridge" "global_mapper" "fla_msgs" "snapstack_msgs")
set(global_mapper_ros_TEST_DEPENDS )
set(global_mapper_ros_DOC_DEPENDS )
set(global_mapper_ros_URL_WEBSITE "")
set(global_mapper_ros_URL_BUGTRACKER "")
set(global_mapper_ros_URL_REPOSITORY "")
set(global_mapper_ros_DEPRECATED "")