set(_CATKIN_CURRENT_PACKAGE "global_planner")
set(global_planner_VERSION "0.0.0")
set(global_planner_MAINTAINER "sangita <sangita@todo.todo>")
set(global_planner_PACKAGE_FORMAT "2")
set(global_planner_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "snapstack_msgs" "nav_msgs" "map_simulator" "octomapListner" "octomap")
set(global_planner_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(global_planner_BUILDTOOL_DEPENDS "catkin")
set(global_planner_BUILDTOOL_EXPORT_DEPENDS )
set(global_planner_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "snapstack_msgs" "nav_msgs" "map_simulator" "octomap" "octomapListner")
set(global_planner_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "snapstack_msgs" "nav_msgs" "map_simulator" "octomap" "octomapListner")
set(global_planner_TEST_DEPENDS )
set(global_planner_DOC_DEPENDS )
set(global_planner_URL_WEBSITE "")
set(global_planner_URL_BUGTRACKER "")
set(global_planner_URL_REPOSITORY "")
set(global_planner_DEPRECATED "")