// Generated by gencpp from file snapstack_msgs/CommAge.msg
// DO NOT EDIT!


#ifndef SNAPSTACK_MSGS_MESSAGE_COMMAGE_H
#define SNAPSTACK_MSGS_MESSAGE_COMMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace snapstack_msgs
{
template <class ContainerAllocator>
struct CommAge_
{
  typedef CommAge_<ContainerAllocator> Type;

  CommAge_()
    : header()
    , vicon_age_secs(0.0)
    , goal_age_secs(0.0)  {
    }
  CommAge_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vicon_age_secs(0.0)
    , goal_age_secs(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _vicon_age_secs_type;
  _vicon_age_secs_type vicon_age_secs;

   typedef float _goal_age_secs_type;
  _goal_age_secs_type goal_age_secs;





  typedef boost::shared_ptr< ::snapstack_msgs::CommAge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snapstack_msgs::CommAge_<ContainerAllocator> const> ConstPtr;

}; // struct CommAge_

typedef ::snapstack_msgs::CommAge_<std::allocator<void> > CommAge;

typedef boost::shared_ptr< ::snapstack_msgs::CommAge > CommAgePtr;
typedef boost::shared_ptr< ::snapstack_msgs::CommAge const> CommAgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snapstack_msgs::CommAge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snapstack_msgs::CommAge_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::snapstack_msgs::CommAge_<ContainerAllocator1> & lhs, const ::snapstack_msgs::CommAge_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vicon_age_secs == rhs.vicon_age_secs &&
    lhs.goal_age_secs == rhs.goal_age_secs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::snapstack_msgs::CommAge_<ContainerAllocator1> & lhs, const ::snapstack_msgs::CommAge_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace snapstack_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::snapstack_msgs::CommAge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snapstack_msgs::CommAge_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snapstack_msgs::CommAge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snapstack_msgs::CommAge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snapstack_msgs::CommAge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snapstack_msgs::CommAge_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snapstack_msgs::CommAge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37ee5d091cfb61db7a1dcd668b6244ed";
  }

  static const char* value(const ::snapstack_msgs::CommAge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37ee5d091cfb61dbULL;
  static const uint64_t static_value2 = 0x7a1dcd668b6244edULL;
};

template<class ContainerAllocator>
struct DataType< ::snapstack_msgs::CommAge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snapstack_msgs/CommAge";
  }

  static const char* value(const ::snapstack_msgs::CommAge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snapstack_msgs::CommAge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 vicon_age_secs\n"
"float32 goal_age_secs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::snapstack_msgs::CommAge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snapstack_msgs::CommAge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vicon_age_secs);
      stream.next(m.goal_age_secs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommAge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snapstack_msgs::CommAge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snapstack_msgs::CommAge_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vicon_age_secs: ";
    Printer<float>::stream(s, indent + "  ", v.vicon_age_secs);
    s << indent << "goal_age_secs: ";
    Printer<float>::stream(s, indent + "  ", v.goal_age_secs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAPSTACK_MSGS_MESSAGE_COMMAGE_H
