// Generated by gencpp from file snapstack_msgs/QuadFlightMode.msg
// DO NOT EDIT!


#ifndef SNAPSTACK_MSGS_MESSAGE_QUADFLIGHTMODE_H
#define SNAPSTACK_MSGS_MESSAGE_QUADFLIGHTMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace snapstack_msgs
{
template <class ContainerAllocator>
struct QuadFlightMode_
{
  typedef QuadFlightMode_<ContainerAllocator> Type;

  QuadFlightMode_()
    : header()
    , mode(0)  {
    }
  QuadFlightMode_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(NOT_FLYING)
  #undef NOT_FLYING
#endif
#if defined(_WIN32) && defined(TAKEOFF)
  #undef TAKEOFF
#endif
#if defined(_WIN32) && defined(LAND)
  #undef LAND
#endif
#if defined(_WIN32) && defined(INIT)
  #undef INIT
#endif
#if defined(_WIN32) && defined(GO)
  #undef GO
#endif
#if defined(_WIN32) && defined(ESTOP)
  #undef ESTOP
#endif
#if defined(_WIN32) && defined(KILL)
  #undef KILL
#endif

  enum {
    NOT_FLYING = 0u,
    TAKEOFF = 1u,
    LAND = 2u,
    INIT = 3u,
    GO = 4u,
    ESTOP = 5u,
    KILL = 6u,
  };


  typedef boost::shared_ptr< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> const> ConstPtr;

}; // struct QuadFlightMode_

typedef ::snapstack_msgs::QuadFlightMode_<std::allocator<void> > QuadFlightMode;

typedef boost::shared_ptr< ::snapstack_msgs::QuadFlightMode > QuadFlightModePtr;
typedef boost::shared_ptr< ::snapstack_msgs::QuadFlightMode const> QuadFlightModeConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::snapstack_msgs::QuadFlightMode_<ContainerAllocator1> & lhs, const ::snapstack_msgs::QuadFlightMode_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::snapstack_msgs::QuadFlightMode_<ContainerAllocator1> & lhs, const ::snapstack_msgs::QuadFlightMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace snapstack_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5d2af0214158b4bd2c1a618cd003a25";
  }

  static const char* value(const ::snapstack_msgs::QuadFlightMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5d2af0214158b4bULL;
  static const uint64_t static_value2 = 0xd2c1a618cd003a25ULL;
};

template<class ContainerAllocator>
struct DataType< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "snapstack_msgs/QuadFlightMode";
  }

  static const char* value(const ::snapstack_msgs::QuadFlightMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 mode\n"
"uint8 NOT_FLYING   = 0\n"
"uint8 TAKEOFF      = 1\n"
"uint8 LAND	       = 2\n"
"uint8 INIT 	       = 3\n"
"uint8 GO		   = 4\n"
"uint8 ESTOP        = 5\n"
"uint8 KILL		   = 6\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::snapstack_msgs::QuadFlightMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadFlightMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::snapstack_msgs::QuadFlightMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::snapstack_msgs::QuadFlightMode_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SNAPSTACK_MSGS_MESSAGE_QUADFLIGHTMODE_H
