set(_CATKIN_CURRENT_PACKAGE "map_simulator")
set(map_simulator_VERSION "0.0.0")
set(map_simulator_MAINTAINER "sangita <sangita@todo.todo>")
set(map_simulator_PACKAGE_FORMAT "2")
set(map_simulator_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "message_generation" "octomap")
set(map_simulator_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(map_simulator_BUILDTOOL_DEPENDS "catkin")
set(map_simulator_BUILDTOOL_EXPORT_DEPENDS )
set(map_simulator_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "message_runtime" "octomap")
set(map_simulator_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "message_runtime" "octomap")
set(map_simulator_TEST_DEPENDS )
set(map_simulator_DOC_DEPENDS )
set(map_simulator_URL_WEBSITE "")
set(map_simulator_URL_BUGTRACKER "")
set(map_simulator_URL_REPOSITORY "")
set(map_simulator_DEPRECATED "")