#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/sangita/project_ws/AER1516/devel_isolated/map_simulator:/home/sangita/project_ws/AER1516/devel_isolated/jps3d:/home/sangita/project_ws/AER1516/devel_isolated/depthmap_filter:/home/sangita/project_ws/AER1516/devel_isolated/fla_utils:/home/sangita/project_ws/AER1516/devel_isolated/fla_msgs:/home/sangita/project_ws/AER1516/devel_isolated/faster_msgs:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_utils:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_msgs:/home/sangita/project_ws/AER1516/devel_isolated/convex_decomposer:/home/sangita/project_ws/AER1516/devel_isolated/catkin_simple:/home/sangita/project_ws/AER1516/devel_isolated/acl_sim:/home/sangita/project_ws/AER1516/devel:/opt/ros/melodic:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper:/home/sangita/project_ws/AER1516/devel_isolated/decomp_util'
export LD_LIBRARY_PATH='/home/sangita/project_ws/AER1516/devel_isolated/jps3d/lib:/home/sangita/project_ws/AER1516/devel_isolated/depthmap_filter/lib:/home/sangita/project_ws/AER1516/devel_isolated/fla_utils/lib:/home/sangita/project_ws/AER1516/devel_isolated/fla_msgs/lib:/home/sangita/project_ws/AER1516/devel_isolated/faster_msgs/lib:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_utils/lib:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_msgs/lib:/home/sangita/project_ws/AER1516/devel_isolated/convex_decomposer/lib:/home/sangita/project_ws/AER1516/devel_isolated/catkin_simple/lib:/home/sangita/project_ws/AER1516/devel_isolated/acl_sim/lib:/home/sangita/project_ws/AER1516/devel/lib:/opt/ros/melodic/lib:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper/lib:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper/lib/x86_64-linux-gnu'
export PATH='/opt/ros/melodic/bin:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper/bin:/home/sangita/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/sangita/project_ws/AER1516/devel_isolated/depthmap_filter/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/fla_utils/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/fla_msgs/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/faster_msgs/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_utils/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_msgs/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/convex_decomposer/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/catkin_simple/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/acl_sim/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper/lib/pkgconfig:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/sangita/project_ws/AER1516/devel_isolated/fla_msgs/lib/python2.7/dist-packages:/home/sangita/project_ws/AER1516/devel_isolated/faster_msgs/lib/python2.7/dist-packages:/home/sangita/project_ws/AER1516/devel_isolated/decomp_ros_msgs/lib/python2.7/dist-packages:/home/sangita/project_ws/AER1516/devel_isolated/convex_decomposer/lib/python2.7/dist-packages:/home/sangita/project_ws/AER1516/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/sangita/project_ws/AER1516/devel_isolated/global_mapper/lib/python2.7/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/sangita/project_ws/AER1516/devel_isolated/map_simulator/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/sangita/project_ws/AER1516/src/map_simulator:/home/sangita/project_ws/AER1516/devel_isolated/jps3d/share:$ROS_PACKAGE_PATH"